baseURL = "http://www.example.com"
title = "Kenichiro's Portfolio"
theme = "hugo-coder"
languageCode = "ja"
defaultContentLanguage = "ja"
paginate = 20
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
author = "Kenichiro Tsuji"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Kenichiro's personal website"
keywords = "computer science,engineer"
info = ["Computer Science, Engineer"]
avatarURL = "images/topPhoto.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "2006-01"
since = 2023
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false

# font = "Arial, sans-serif"
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
# customCSS = ["css/custom_style.css"]
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/2Gken1029/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 2
url = "https://twitter.com/2Gken1029/"

[[params.social]]
name = "Qiita"
icon = "fa fa-2x fa-link"
weight = 3
url = "https://qiita.com/2Gken1029"

[languages.ja]
# languageName = ":en:"

[[languages.ja.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.ja.menu.main]]
name = "Career"
weight = 2
url = "careers/"

[[languages.ja.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.ja.menu.main]]
name = "Contact me"
weight = 4
url = "contact/"